#!/bin/bash

CURRENT_DIR=`pwd`
IMAGES_DIR=${CURRENT_DIR}/bin/
VERSIONS=${CURRENT_DIR}/VERSIONS

RTEMS_GIT_DIR=../rtems-milkymist.git
LEKERNEL_GIT_DIR=../lekernel

get-feeds-revision() {
  cd $1
  repo=$(git config -l | grep remote.origin.url | cut -d "=" -f 2)
  rev=$(git log | head -n 1 | cut -b8-)
  branch=$(git branch | grep "*" | cut -b3-)
  echo "${repo}  ${branch} ${rev}" >> ${VERSIONS}
  cd ${CURRENT_DIR}
}


echo "prepare, mkdir ..."
rm -tf ${IMAGES_DIR}
mkdir -p ${IMAGES_DIR}


echo "update git ..."
make -C compile-rtems/ git-update
make -C compile-flickernoise/ update_lekernel_git


echo "get git versions ..."
rm -rf ${VERSIONS}
get-feeds-revision ${LEKERNEL_GIT_DIR}/milkymist.git
get-feeds-revision ${LEKERNEL_GIT_DIR}/mtk.git
get-feeds-revision ${LEKERNEL_GIT_DIR}/liboscparse.git
get-feeds-revision ${LEKERNEL_GIT_DIR}/rtems-yaffs2.git
get-feeds-revision ${LEKERNEL_GIT_DIR}/flickernoise.git
get-feeds-revision ${LEKERNEL_GIT_DIR}/m1testing.git
get-feeds-revision ${RTEMS_GIT_DIR}
get-feeds-revision .


echo "compile ..."
make -C ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash
make -C compile-rtems 
make -C compile-flickernoise clean
make -C compile-flickernoise flickernoise.fbi
make -C compile-flickernoise flickernoise-pdf.fbiz
make -C compile-flickernoise boot.bin


echo "copy images to bin/ ..."
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/fjmem.bit ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/standby.fpg ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/soc.fpg ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/bios.bin ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/splash.raw ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/soc-rescue.fpg ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/bios-rescue.bin ${IMAGES_DIR}
cp ${LEKERNEL_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/splash-rescue.raw ${IMAGES_DIR}

cp compile-flickernoise/flickernoise.fbi ${IMAGES_DIR}
cp compile-flickernoise/flickernoise-pdf.fbiz ${IMAGES_DIR}
cp compile-flickernoise/boot.bin ${IMAGES_DIR}

echo "build data patitions ..."
rm -rf data.flash5
mkdir -p data.flash5

cp -rf ${LEKERNEL_GIT_DIR}/flickernoise.git/patches ./data.flash5
wget http://www.milkymist.org/wiki/images/9/99/Comet.png -O ./data.flash5/Comet.png

make -C ${LEKERNEL_GIT_DIR}/rtems-yaffs2.git/utils/mm-mkyaffs2image
${LEKERNEL_GIT_DIR}/rtems-yaffs2.git/utils/mm-mkyaffs2image data.flash5 ${IMAGES_DIR}/data.flash5.bin convert

echo "generate md5sum ..."
(cd ${IMAGES_DIR}; md5sum * > ${CURRENT_DIR}/md5sum)
mv ${VERSIONS} md5sum ${IMAGES_DIR};