#!/bin/bash

set -e

CURRENT_DIR=`pwd`
IMAGES_DIR=${CURRENT_DIR}/bin
VERSIONS=${CURRENT_DIR}/VERSIONS

MILKYMIST_GIT_DIR=../milkymist

get-feeds-revision() {
  cd $1
  repo=$(git config -l | grep remote.origin.url | cut -d "=" -f 2)
  rev=$(git log | head -n 1 | cut -b8-)
  branch=$(git branch | grep "*" | cut -b3-)
  echo "${repo}  ${branch} ${rev}" >> ${VERSIONS}
  cd ${CURRENT_DIR}
}


echo "prepare, mkdir ..."
mv ${IMAGES_DIR} ${IMAGES_DIR}.backup
mkdir -p ${IMAGES_DIR}


echo "update git ..."
make -C compile-flickernoise/ milkymist-git-update


echo "get git versions ..."
rm -f ${VERSIONS}
get-feeds-revision ${MILKYMIST_GIT_DIR}/milkymist.git
get-feeds-revision ${MILKYMIST_GIT_DIR}/rtems-milkymist.git
get-feeds-revision ${MILKYMIST_GIT_DIR}/mtk.git
get-feeds-revision ${MILKYMIST_GIT_DIR}/liboscparse.git
get-feeds-revision ${MILKYMIST_GIT_DIR}/rtems-yaffs2.git
get-feeds-revision ${MILKYMIST_GIT_DIR}/flickernoise.git
get-feeds-revision .


echo "compile ..."
(cd ${MILKYMIST_GIT_DIR}/milkymist.git && ./clean_all.sh)
make -C ${MILKYMIST_GIT_DIR}/milkymist.git/tools

#the Xilinx libs(libstdc++.so.6) have some conflict
(source /opt/Xilinx/13.1/ISE_DS/settings64.sh && \
 make -C ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash)

export PATH=${MILKYMIST_GIT_DIR}/milkymist.git/tools:$PATH
make -C compile-flickernoise clean
make -C compile-flickernoise flickernoise.fbi


echo "copy images to bin/ ..."
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/fjmem.bit ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/standby.fpg ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/soc.fpg ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/bios.bin ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/splash.raw ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/soc-rescue.fpg ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/bios-rescue.bin ${IMAGES_DIR}
cp ${MILKYMIST_GIT_DIR}/milkymist.git/boards/milkymist-one/flash/splash-rescue.raw ${IMAGES_DIR}

cp compile-flickernoise/flickernoise.fbi ${IMAGES_DIR}

echo "build data patitions ..."
mkdir -p data.flash5
mkdir -p data.flash5/patches
find ${MILKYMIST_GIT_DIR}/flickernoise.git/patches -name "*.fnp" -exec cp {} ./data.flash5/patches \;

make -C ${MILKYMIST_GIT_DIR}/rtems-yaffs2.git/utils mm-mkyaffs2image
${MILKYMIST_GIT_DIR}/rtems-yaffs2.git/utils/mm-mkyaffs2image data.flash5 ${IMAGES_DIR}/data.flash5.bin convert
chmod 644 ${IMAGES_DIR}/data.flash5.bin

echo "generate md5sum ..."
(cd ${IMAGES_DIR}; md5sum --binary * > ${CURRENT_DIR}/md5sums)
mv ${VERSIONS} md5sums ${IMAGES_DIR}
cp reflash_m1.sh ${IMAGES_DIR}


echo "build documents ..."
mkdir -p ${IMAGES_DIR}/doc
make -C ${MILKYMIST_GIT_DIR}/flickernoise.git/doc/
cp -f ${MILKYMIST_GIT_DIR}/flickernoise.git/doc/*.pdf ${IMAGES_DIR}/doc